=== renaner123/XML_JSON_JAVA/src/main/resources/pedido.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="pedido">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="cliente" type="xs:string"/>
      <xs:element name="destino">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="nome" type="xs:string"/>
            <xs:element name="endereco" type="xs:string"/>
            <xs:element name="cidade" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="item" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="produto" type="xs:string"/>
            <xs:element name="quantidade" type="xs:positiveInteger"/>
            <xs:element name="preco" type="xs:decimal"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required"/>
  </xs:complexType>
</xs:element>

</xs:schema>

=== renaner123/XML_JSON_JAVA/src/main/resources/pedido.xml
<?xml version="1.0" encoding="UTF-8"?>

<pedido id="1"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="pedido.xsd">
  <cliente>João</cliente>
  <destino>
    <nome>Maria</nome>
    <endereco>SCS 1</endereco>
    <cidade>Brasília</cidade>
  </destino>
  <item>
    <produto>Apostila Java</produto>
    <quantidade>1</quantidade>
    <preco>10.90</preco>
  </item>
  <item>
    <produto>Apostila Javascript</produto>
    <quantidade>1</quantidade>
    <preco>9.90</preco>
  </item>
</pedido>
